apiVersion: v1
kind: Service
metadata:
  name: kong-metrics
  namespace: kong
  labels:
    app: prometheus
spec:
  selector:
    app: ingress-kong
  ports:
  - name: metrics
    protocol: TCP
    port: 8100
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong
  labels:
    app: ingress-kong
spec:
  jobLabel: ingress-kong
  selector:
    matchExpressions:
    - {key: app, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
    - kong
  endpoints:
  - port: metrics
    interval: 30s