apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: logging
  labels:
    app: logging
spec:
  version: 7.10.2
  count: 1
  elasticsearchRef:
    name: logging
    namespace: default
  http:
    tls:
      selfSignedCertificate:
        disabled: true