apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: kube-log
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.8.1
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        ports:
        # - name: udp
        #   containerPort: 5000
        #   protocol: UDP
        # - name: tcp
        #   containerPort: 5000
        #   protocol: TCP
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: logstash-config
          mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-config
        configMap:
          name: logstash