apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
  labels:
    app: webapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: index-volume
          mountPath: /usr/share/nginx/html/
      volumes:
      - name: index-volume
        configMap:
          name: webapp2
---
apiVersion: v1
kind: Service
metadata:
  name: webapp2
spec:
  selector:
    app: webapp2
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp2
data:
  index.html: |
    <h1>Web Application 2</h1>