apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-ingress
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
    - kong
  selector:
    matchLabels:
      app: ingress-kong
  endpoints:
  - port: admin