apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cms.project }}-config
data:
  hostname: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}.default.svc.cluster.local
  database: {{ .Values.cms.database.container.database }}
  type: mysql