apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
  labels:
    app: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
  template:
    metadata:
      labels:
        app: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
    spec:
      containers:
      - name: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
        image: {{ .Values.cms.application.container.image }}
        env:
        - name: database__connection__user
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cms.project }}-secret
              key: username
        - name: database__connection__password
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cms.project }}-secret
              key: password
        - name: database__connection__database
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.cms.project }}-config
              key: database
        - name: database__connection__host
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.cms.project }}-config
              key: hostname
        - name: database__client
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.cms.project }}-config
              key: type
        ports:
        - containerPort: 2368