apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
  annotations:
    kubernetes.io/ingress.class: "kong"
spec:
  rules:
  - host: ghost.demo.local
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.cms.project }}-{{ .Values.cms.application.service }}
          servicePort: 2368