apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cms.project }}-secret
data:
  root: {{ .Values.cms.database.container.root }}
  username: {{ .Values.cms.database.container.username }}
  password: {{ .Values.cms.database.container.password }}
type: Opaque