apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}
  serviceName: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}
    spec:
      containers:
      - name: {{ .Values.cms.project }}-{{ .Values.cms.database.service }}
        image: {{ .Values.cms.database.container.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cms.project }}-secret
              key: root
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cms.project }}-secret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cms.project }}-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.cms.project }}-config
              key: database
        ports:
        - containerPort: 3306