# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: developer
# ---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
   name: developer-pod-reader
   namespace: default
subjects:
 - kind: ServiceAccount
   name: developer
   namespace: default
roleRef:
   kind: Role
   name: pod-reader
   apiGroup: rbac.authorization.k8s.io