apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: webapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: web1
        image: docker.pkg.github.com/warapong-pj/kubernetes/web1:dev
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: github-com
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1
spec:
  selector:
    app: webapp1
  ports:
  - protocol: TCP
    port: 80
  type: ClusterIP