apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /web1
        pathType: Prefix
        backend:
          service:
            name: webapp1
            port:
              number: 80
      - path: /web2
        pathType: Prefix
        backend:
          service:
            name: webapp2
            port:
              number: 80